// Code generated by "stringer -type NodeValueType"; DO NOT EDIT.

package jsonwalk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Nil-0]
	_ = x[Bool-1]
	_ = x[String-2]
	_ = x[Float64-3]
	_ = x[Array-4]
	_ = x[Map-5]
}

const _NodeValueType_name = "NilBoolStringFloat64ArrayMap"

var _NodeValueType_index = [...]uint8{0, 3, 7, 13, 20, 25, 28}

func (i NodeValueType) String() string {
	if i < 0 || i >= NodeValueType(len(_NodeValueType_index)-1) {
		return "NodeValueType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeValueType_name[_NodeValueType_index[i]:_NodeValueType_index[i+1]]
}
